// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtbrqxclmpddndmrghyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0YnJxeGNsbXBkZG5kbXJnaHlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NzY3NDgsImV4cCI6MjA1NzI1Mjc0OH0.e_8pche58Nf_7O2lIBQTwQ9DWbYmTpq5y_3ROpkd2VA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);